baseURL = "https://aihub.bitmagic.space/"
#title = "Hugo Themes"
author = "瑞东"
copyright = "Copyright © 2023"
paginate = 12
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
title = 'Aihub'
theme = "alexa-portfolio"

enableRobotsTXT = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
# favicon = "/images/fav.png"
home_title = "欢迎来到 Aihub"
home_subtitle = "发现Ai相关的应用、提示和模型"
home_description = "AIhub：连接你和人工智能的桥梁，探索未来的无限可能！"
website = ""
github = "https://github.com/weekend-project-space"
twitter = "https://twitter.com/SUNXYZCHINA"
home_btn = "提交更多"
Description = "发现Ai相关的应用、提示和模型,Aihub 连接你和人工智能的桥梁，探索未来的无限可能！"
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
