baseURL = "https://aihub.bitmagic.space/"
#title = "Hugo Themes"
author = "瑞东"
copyright = "Copyright © 2023"
paginate = 12
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
title = 'Aihub'
theme = "alexa-portfolio"

enableRobotsTXT = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
	# favicon = "/images/fav.png"
home_title = "欢迎来到 Aihub"
home_subtitle = "展示Ai相关的应用和模型"
home_description = "Ai相关的技术革命正在逼近，在这里找到你感兴趣的工具吧"
website = ""
github = "https://github.com/weekend-project-space"
twitter = "https://twitter.com/SUNXYZCHINA"
home_btn = "提交更多"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
